#!/bin/bash

ros2 bag record \
/tf \
/camera/camera/color/camera_info \
/camera/camera/color/image_raw \
/camera/camera/color/metadata \
/snap/bsk_mpc/predicted_path \
/snap/bsk_mpc/setpoint_pose \
/snap/bsk_mpc/vehicle_angular_velocity \
/snap/bsk_mpc/vehicle_angular_velocity_ref \
/snap/bsk_mpc/vehicle_pose \
/snap/bsk_mpc/vehicle_pose_ref \
/snap/bsk_mpc/vehicle_velocity \
/snap/bsk_mpc/vehicle_velocity_ref \
/snap/fmu/in/offboard_control_mode \
/snap/fmu/in/vehicle_visual_odometry \
/snap/fmu/in/vehicle_thrust_setpoint \
/snap/fmu/in/vehicle_torque_setpoint \
/snap/fmu/out/vehicle_control_mode \
/snap/fmu/out/vehicle_status_v1 \
/snap/fmu/out/actuator_motors \
/snap/odom \
/crackle/bsk_mpc/predicted_path \
/crackle/bsk_mpc/setpoint_pose \
/crackle/bsk_mpc/vehicle_angular_velocity \
/crackle/bsk_mpc/vehicle_angular_velocity_ref \
/crackle/bsk_mpc/vehicle_pose \
/crackle/bsk_mpc/vehicle_pose_ref \
/crackle/bsk_mpc/vehicle_velocity \
/crackle/bsk_mpc/vehicle_velocity_ref \
/crackle/fmu/in/offboard_control_mode \
/crackle/fmu/in/vehicle_visual_odometry \
/crackle/fmu/in/vehicle_thrust_setpoint \
/crackle/fmu/in/vehicle_torque_setpoint \
/crackle/fmu/out/vehicle_control_mode \
/crackle/fmu/out/vehicle_status_v1 \
/crackle/fmu/out/actuator_motors \
/crackle/odom \
/pop/bsk_mpc/predicted_path \
/pop/bsk_mpc/setpoint_pose \
/pop/bsk_mpc/vehicle_angular_velocity \
/pop/bsk_mpc/vehicle_angular_velocity_ref \
/pop/bsk_mpc/vehicle_pose \
/pop/bsk_mpc/vehicle_pose_ref \
/pop/bsk_mpc/vehicle_velocity \
/pop/bsk_mpc/vehicle_velocity_ref \
/pop/fmu/in/offboard_control_mode \
/pop/fmu/in/vehicle_visual_odometry \
/pop/fmu/in/vehicle_thrust_setpoint \
/pop/fmu/in/vehicle_torque_setpoint \
/pop/fmu/out/vehicle_control_mode \
/pop/fmu/out/vehicle_status_v1 \
/pop/fmu/out/actuator_motors \
/pop/odom \
